services:
    url_shortener_cache:
        image: redis/redis-stack-server
        ports:
            - 6379:6379

    # (reference): https://hub.docker.com/_/postgres
    url_shortener_db:
        image: postgres
        restart: always
        # set shared memory limit
        shm_size: 128mb
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=url_shortener
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ${USERPROFILE}/.url_shortnener_pgdata:/var/lib/postgresql/data

    url_shortener_app:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        depends_on:
            - url_shortener_db
            - url_shortener_cache
        ports:
            - 8000:8000
        develop:
            watch:
                - action: sync
                  path: .
                  target: /app
                  ignore:
                      - node_modules

                - action: rebuild # rebuild if package.json changes
                  path: package.json
